---
http_interactions:
- request:
    method: get
    uri: http://api.wunderground.com/api/f9bc7bc5873d396b/geolookup/q/autoip.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - f9bc7bc5873d396b
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache/2.2.15 (CentOS)
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      X-Creationtime:
      - '0.089'
      Last-Modified:
      - Thu, 26 May 2016 18:22:00 GMT
      Content-Type:
      - application/json; charset=UTF-8
      Vary:
      - Accept-Encoding
      Expires:
      - Thu, 26 May 2016 18:22:00 GMT
      Cache-Control:
      - max-age=0, no-cache
      Pragma:
      - no-cache
      Date:
      - Thu, 26 May 2016 18:22:00 GMT
      Content-Length:
      - '6635'
      Connection:
      - keep-alive
      Set-Cookie:
      - DT=1464286920:13069:365-dell-c9; path=/; expires=Fri, 01-Jan-2020 00:00:00
        GMT; domain=.wunderground.com
      - Prefs=FAVS:1|WXSN:1|PWSOBS:1|WPHO:1|PHOT:1|RADC:0|RADALL:0|HIST0:NULL|GIFT:1|PHOTOTHUMBS:50|;
        path=/; expires=Fri, 01-Jan-2020 00:00:00 GMT; domain=.wunderground.com
    body:
      encoding: UTF-8
      string: "\n{\n  \"response\": {\n  \"version\":\"0.1\",\n  \"termsofService\":\"http://www.wunderground.com/weather/api/d/terms.html\",\n
        \ \"features\": {\n  \"geolookup\": 1\n  }\n\t}\n\t\t,\t\"location\": {\n\t\t\"type\":\"CITY\",\n\t\t\"country\":\"US\",\n\t\t\"country_iso3166\":\"US\",\n\t\t\"country_name\":\"USA\",\n\t\t\"state\":\"CO\",\n\t\t\"city\":\"Denver\",\n\t\t\"tz_short\":\"MDT\",\n\t\t\"tz_long\":\"America/Denver\",\n\t\t\"lat\":\"39.74983978\",\n\t\t\"lon\":\"-104.99559784\",\n\t\t\"zip\":\"80202\",\n\t\t\"magic\":\"1\",\n\t\t\"wmo\":\"99999\",\n\t\t\"l\":\"/q/zmw:80202.1.99999\",\n\t\t\"requesturl\":\"US/CO/Denver.html\",\n\t\t\"wuiurl\":\"http://www.wunderground.com/US/CO/Denver.html\",\n\t\t\"nearby_weather_stations\":
        {\n\t\t\"airport\": {\n\t\t\"station\": [\n\t\t{ \"city\":\"Denver Centennial\",
        \"state\":\"CO\", \"country\":\"US\", \"icao\":\"KAPA\", \"lat\":\"39.55990982\",
        \"lon\":\"-104.84841156\" }\n\t\t,{ \"city\":\"Denver\", \"state\":\"CO\",
        \"country\":\"US\", \"icao\":\"KDEN\", \"lat\":\"39.84658051\", \"lon\":\"-104.65621948\"
        }\n\t\t,{ \"city\":\"Aurora\", \"state\":\"CO\", \"country\":\"US\", \"icao\":\"KBKF\",
        \"lat\":\"39.71331024\", \"lon\":\"-104.75805664\" }\n\t\t,{ \"city\":\"Broomfield\",
        \"state\":\"CO\", \"country\":\"US\", \"icao\":\"KBJC\", \"lat\":\"39.90084839\",
        \"lon\":\"-105.10417175\" }\n\t\t]\n\t\t}\n\t\t,\n\t\t\"pws\": {\n\t\t\"station\":
        [\n\t\t{\n\t\t\"neighborhood\":\"Central Business District\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE223\",\n\t\t\"lat\":39.746429,\n\t\t\"lon\":-104.997963,\n\t\t\"distance_km\":0,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Ballpark\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE187\",\n\t\t\"lat\":39.752403,\n\t\t\"lon\":-104.991058,\n\t\t\"distance_km\":0,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Larimer\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE189\",\n\t\t\"lat\":39.753296,\n\t\t\"lon\":-104.991394,\n\t\t\"distance_km\":0,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Geography
        and Env. Sciences, CU Denver\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE78\",\n\t\t\"lat\":39.745201,\n\t\t\"lon\":-105.002403,\n\t\t\"distance_km\":0,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Capitol
        Hill\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE145\",\n\t\t\"lat\":39.739201,\n\t\t\"lon\":-104.984703,\n\t\t\"distance_km\":1,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"San
        Rafael Neighborhood\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE131\",\n\t\t\"lat\":39.751591,\n\t\t\"lon\":-104.977402,\n\t\t\"distance_km\":1,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Ballpark\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE155\",\n\t\t\"lat\":39.763519,\n\t\t\"lon\":-104.988846,\n\t\t\"distance_km\":1,\n\t\t\"distance_mi\":0\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Northwest\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE119\",\n\t\t\"lat\":39.754841,\n\t\t\"lon\":-105.014832,\n\t\t\"distance_km\":1,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Capitol
        HIll\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE218\",\n\t\t\"lat\":39.734711,\n\t\t\"lon\":-104.977921,\n\t\t\"distance_km\":2,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Whittier\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE216\",\n\t\t\"lat\":39.752762,\n\t\t\"lon\":-104.968063,\n\t\t\"distance_km\":2,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Highland\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE208\",\n\t\t\"lat\":39.765514,\n\t\t\"lon\":-105.016136,\n\t\t\"distance_km\":2,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Cheesman
        Park\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE206\",\n\t\t\"lat\":39.730705,\n\t\t\"lon\":-104.970947,\n\t\t\"distance_km\":2,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Alamo
        Placita\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE194\",\n\t\t\"lat\":39.724731,\n\t\t\"lon\":-104.977036,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Cheesman
        Park\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE115\",\n\t\t\"lat\":39.735161,\n\t\t\"lon\":-104.962387,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":1\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"West
        Highland\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE86\",\n\t\t\"lat\":39.768597,\n\t\t\"lon\":-105.026672,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"West
        Colfax at King St\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE97\",\n\t\t\"lat\":39.739059,\n\t\t\"lon\":-105.033760,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Sloans
        Lake\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE213\",\n\t\t\"lat\":39.749737,\n\t\t\"lon\":-105.036652,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"SLOHI
        W 29th Ave and Perry St\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE120\",\n\t\t\"lat\":39.757690,\n\t\t\"lon\":-105.038879,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"West
        Denver\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE11\",\n\t\t\"lat\":39.752911,\n\t\t\"lon\":-105.040840,\n\t\t\"distance_km\":3,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"MISC\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"MDMNC2\",\n\t\t\"lat\":39.753170,\n\t\t\"lon\":-104.948898,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Perry
        St station\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE235\",\n\t\t\"lat\":39.733143,\n\t\t\"lon\":-105.038193,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Berkeley\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE146\",\n\t\t\"lat\":39.773548,\n\t\t\"lon\":-105.033119,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"West
        Highland\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE118\",\n\t\t\"lat\":39.769497,\n\t\t\"lon\":-105.038986,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Country
        Club\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE243\",\n\t\t\"lat\":39.720005,\n\t\t\"lon\":-104.959892,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"West
        Highlands\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE217\",\n\t\t\"lat\":39.762772,\n\t\t\"lon\":-105.045959,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Denver
        Country Club / Wash Park\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE98\",\n\t\t\"lat\":39.713993,\n\t\t\"lon\":-104.970200,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Congress
        Park\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE271\",\n\t\t\"lat\":39.735527,\n\t\t\"lon\":-104.944565,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t},\n\t\t{\n\t\t\"neighborhood\":\"Wash
        Park West\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"country\":\"US\",\n\t\t\"id\":\"KCODENVE236\",\n\t\t\"lat\":39.708130,\n\t\t\"lon\":-104.981133,\n\t\t\"distance_km\":4,\n\t\t\"distance_mi\":2\n\t\t}\n\t\t]\n\t\t}\n\t\t}\n\t}\n}\n"
    http_version: 
  recorded_at: Thu, 26 May 2016 18:22:00 GMT
- request:
    method: get
    uri: http://api.wunderground.com/api/f9bc7bc5873d396b/conditions/q/80202.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - f9bc7bc5873d396b
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache/2.2.15 (CentOS)
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      X-Creationtime:
      - '0.051'
      Last-Modified:
      - Thu, 26 May 2016 18:22:00 GMT
      Content-Type:
      - application/json; charset=UTF-8
      Vary:
      - Accept-Encoding
      Expires:
      - Thu, 26 May 2016 18:22:00 GMT
      Cache-Control:
      - max-age=0, no-cache
      Pragma:
      - no-cache
      Date:
      - Thu, 26 May 2016 18:22:00 GMT
      Content-Length:
      - '2678'
      Connection:
      - keep-alive
      Set-Cookie:
      - DT=1464286920:48860:365-dell-c14; path=/; expires=Fri, 01-Jan-2020 00:00:00
        GMT; domain=.wunderground.com
      - Prefs=FAVS:1|WXSN:1|PWSOBS:1|WPHO:1|PHOT:1|RADC:0|RADALL:0|HIST0:NULL|GIFT:1|PHOTOTHUMBS:50|;
        path=/; expires=Fri, 01-Jan-2020 00:00:00 GMT; domain=.wunderground.com
    body:
      encoding: UTF-8
      string: "\n{\n  \"response\": {\n  \"version\":\"0.1\",\n  \"termsofService\":\"http://www.wunderground.com/weather/api/d/terms.html\",\n
        \ \"features\": {\n  \"conditions\": 1\n  }\n\t}\n  ,\t\"current_observation\":
        {\n\t\t\"image\": {\n\t\t\"url\":\"http://icons.wxug.com/graphics/wu2/logo_130x80.png\",\n\t\t\"title\":\"Weather
        Underground\",\n\t\t\"link\":\"http://www.wunderground.com\"\n\t\t},\n\t\t\"display_location\":
        {\n\t\t\"full\":\"Denver, CO\",\n\t\t\"city\":\"Denver\",\n\t\t\"state\":\"CO\",\n\t\t\"state_name\":\"Colorado\",\n\t\t\"country\":\"US\",\n\t\t\"country_iso3166\":\"US\",\n\t\t\"zip\":\"80202\",\n\t\t\"magic\":\"1\",\n\t\t\"wmo\":\"99999\",\n\t\t\"latitude\":\"39.74983978\",\n\t\t\"longitude\":\"-104.99559784\",\n\t\t\"elevation\":\"1600.00000000\"\n\t\t},\n\t\t\"observation_location\":
        {\n\t\t\"full\":\"Geography and Env. Sciences, CU Denver, Denver, Colorado\",\n\t\t\"city\":\"Geography
        and Env. Sciences, CU Denver, Denver\",\n\t\t\"state\":\"Colorado\",\n\t\t\"country\":\"US\",\n\t\t\"country_iso3166\":\"US\",\n\t\t\"latitude\":\"39.745201\",\n\t\t\"longitude\":\"-105.002403\",\n\t\t\"elevation\":\"5225
        ft\"\n\t\t},\n\t\t\"estimated\": {\n\t\t},\n\t\t\"station_id\":\"KCODENVE78\",\n\t\t\"observation_time\":\"Last
        Updated on May 26, 12:20 PM MDT\",\n\t\t\"observation_time_rfc822\":\"Thu,
        26 May 2016 12:20:07 -0600\",\n\t\t\"observation_epoch\":\"1464286807\",\n\t\t\"local_time_rfc822\":\"Thu,
        26 May 2016 12:22:00 -0600\",\n\t\t\"local_epoch\":\"1464286920\",\n\t\t\"local_tz_short\":\"MDT\",\n\t\t\"local_tz_long\":\"America/Denver\",\n\t\t\"local_tz_offset\":\"-0600\",\n\t\t\"weather\":\"Mostly
        Cloudy\",\n\t\t\"temperature_string\":\"62.7 F (17.1 C)\",\n\t\t\"temp_f\":62.7,\n\t\t\"temp_c\":17.1,\n\t\t\"relative_humidity\":\"49%\",\n\t\t\"wind_string\":\"From
        the NW at 2.0 MPH Gusting to 7.0 MPH\",\n\t\t\"wind_dir\":\"NW\",\n\t\t\"wind_degrees\":305,\n\t\t\"wind_mph\":2.0,\n\t\t\"wind_gust_mph\":\"7.0\",\n\t\t\"wind_kph\":3.2,\n\t\t\"wind_gust_kph\":\"11.3\",\n\t\t\"pressure_mb\":\"1009\",\n\t\t\"pressure_in\":\"29.79\",\n\t\t\"pressure_trend\":\"-\",\n\t\t\"dewpoint_string\":\"43
        F (6 C)\",\n\t\t\"dewpoint_f\":43,\n\t\t\"dewpoint_c\":6,\n\t\t\"heat_index_string\":\"NA\",\n\t\t\"heat_index_f\":\"NA\",\n\t\t\"heat_index_c\":\"NA\",\n\t\t\"windchill_string\":\"NA\",\n\t\t\"windchill_f\":\"NA\",\n\t\t\"windchill_c\":\"NA\",\n\t\t\"feelslike_string\":\"62.7
        F (17.1 C)\",\n\t\t\"feelslike_f\":\"62.7\",\n\t\t\"feelslike_c\":\"17.1\",\n\t\t\"visibility_mi\":\"10.0\",\n\t\t\"visibility_km\":\"16.1\",\n\t\t\"solarradiation\":\"156\",\n\t\t\"UV\":\"0.0\",\"precip_1hr_string\":\"0.00
        in ( 0 mm)\",\n\t\t\"precip_1hr_in\":\"0.00\",\n\t\t\"precip_1hr_metric\":\"
        0\",\n\t\t\"precip_today_string\":\"0.00 in (0 mm)\",\n\t\t\"precip_today_in\":\"0.00\",\n\t\t\"precip_today_metric\":\"0\",\n\t\t\"icon\":\"mostlycloudy\",\n\t\t\"icon_url\":\"http://icons.wxug.com/i/c/k/mostlycloudy.gif\",\n\t\t\"forecast_url\":\"http://www.wunderground.com/US/CO/Denver.html\",\n\t\t\"history_url\":\"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCODENVE78\",\n\t\t\"ob_url\":\"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.745201,-105.002403\",\n\t\t\"nowcast\":\"\"\n\t}\n}\n"
    http_version: 
  recorded_at: Thu, 26 May 2016 18:22:00 GMT
recorded_with: VCR 3.0.3
